server:
  port: 8802
  servlet:
    context-path: /api

spring:
  application:
    name: spring-boot-email
  mail:
    host: smtp.126.com
    port: 25
    username: jeremygilbert@126.com
    password: Huawei12
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:/static/

  boot:
    admin:
      client:
        url: http://localhost:8803/admin