version: "3"
services:
   mysql:
     image: mysql:5.6
     volumes:
       - $PWD/config:/etc/mysqlconfig.d
       - $PWD/logs:/logs
       - $PWD/data:/var/lib/mysql
     restart: always
     container_name: mysql
     environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: docker
   redis:
     image: redis:3.2
     volumes:
       - $PWD/data:/data
     restart: always
     container_name: redis
     command:
       redis-server
       --appendonly yes
       --requirepass 123456
   springboot-docker:
     depends_on:
       - mysql
       - redis
     image: jeremy/docker-spring-boot
     ports:
       - "8096:8096"
     restart: always
     container_name: spring-boot-docker
     environment:
       MYSQL_HOST: mysql:3306
       MYSQL_DATABASE: docker
       REDIS_HOST: redis


