spring:
  application:
    name: spring-boot-mybatis
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.198.217:3306/boot_activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  activiti:
    history-level: full
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true


server:
  port: 8011