CREATE TABLE "SYS_LOG" (
   "ID" int(20) NOT NULL ,
   "USERNAME" VARCHAR(50) NULL ,
   "OPERATION" VARCHAR(50 ) NULL ,
   "TIME" int(11) NULL ,
   "METHOD" VARCHAR(200 ) NULL ,
   "PARAMS" VARCHAR(500 ) NULL ,
   "IP" VARCHAR(64) NULL ,
   "CREATE_TIME" DATE NULL
);
