spring:
  application:
    name: spring-boot-mybatis
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz949qd557877lei3o.mysql.rds.aliyuncs.com:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ibest_admin
    password: ibest_admin@2017!hh
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


server:
  port: 8808
  servlet:
    context-path: /api


swagger:
  enabled: true
  title: spring boot mybatis
  description: SPRING-BOOT-MYBATIS
  license: SZ IT - ALL RIGHTS RESERVED
  license-url: http://www.itsz.com/
  base-package: com.itsz
  authorization:
    type: BasicAuth